### PR TITLE
Fix: import `console` explicitly for electron-renderer

### LINKED ISSUE #38: Regression in 0.15.1 (when used in browser context)
I triple-checked and everything else left alone 0.15.1 results in an error while 0.15.0 works, so this must be a regression.

The error happens when plugin manager is used in browser context (Electron renderer) and is thrown by this specific line:

https://github.com/davideicardi/live-plugin-manager/blob/881a95c8a0b5d1895d0d7c32855f2914e9419e6b/src/PluginVm.ts#L438

I’ll try to copy the exact error later, it’s about `console.Console` either missing or not being a constructor.

For now downgraded to 0.15.0.

New user here, nice work!

### PR DESCRIPTION
**Pull request by ylc395**
closed #38. When in electron-renderer, `console` is broswer's console, which does't contain `Console`, so `console.Console` will throw `console.Console is not a constructor`. Import `console` explicitly will fix this.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thank you!
Can you just recompile distribution files by running `npm run src-build`?

**Comment by ylc395** [comment]
@davideicardi Done

**Comment by ylc395** [comment]
@davideicardi any progress?

**Review by davideicardi — APPROVED** [review]

**Comment by davideicardi** [comment]
@ylc395 Thank you! I just published version 0.17.1

**Pull request merged**
