### PR TITLE
Add Bitbucket support

### PR DESCRIPTION
**Pull request by quarenw**
This PR adds support to install packages from Bitbucket both public and private only using Basic auth.

Tests added for inexistant packages and public package. The package used in the public test is from Atlassian but is quite big and takes a long time to run the test. Was not able to find a better package hosted on Bitbucket which is reliable and immediately usable for use in the test.

Private repos is tested and working but as with Github it has not been added to the tests.

My use case for adding this feature is installing private Bitbucket packages from master branch and there is no testing for different branches/commits refs but will be adding it in the future.

### CODE REVIEW

**Comment by quarenw** [comment]
Thank you for the review! Makes sense, updated to use a simple package on Bitbucket. Tests now run a reasonable amount of time.

**Review by davideicardi — APPROVED** [review]

**Comment by davideicardi** [comment]
I see that a test abount concurrency installation has failed. Do you think this can be related to your changes? I don't think so but I need to investigate ...

**Comment by davideicardi** [comment]
Still failing ... strange issue. I will try to investigate.

**Comment by davideicardi** [comment]
I will merge this PR given that the error seems to be unrelated to the change.
We can try to fix it in #72 
Thank you!

**Pull request merged**
