### PR TITLE
Add support for peer dependencies

### PR DESCRIPTION
**Pull request by Randgalt**
For my use-case the plugins will go in separate, self-contained, directories
and, thus, won't have access to peer dependencies. This PR adds an option
to install peer dependencies.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks for the suggestion and PR!

Maybe another solution to solve the same problem is to create an instance of `PluginManager` for each plugin? Do you see problems?

Just to avoid adding complexity if not required...

**Comment by Randgalt** [comment]
A new instance of PluginManager doesn't help as it still won't add the peer dependencies.

**Comment by davideicardi** [comment]
Ah now I have understand ... sorry! to be honest I didn't know about `peerDependencies` feature.

After reading some doc, https://docs.npmjs.com/files/package.json#peerdependencies, it seems that the behavior should not be to install automatically it, but to prevent installation of package if it is not already installed.

Maybe we can by default implement this behavior, rasing a specific exception, and providing all the info for the missing dependencies. So that the client can catch the exception and install these dependencies manually if needed.

Something like (pseudo code):

```typescript
try {
  await manager.install("my-plugin");
} catch (err) {
  if (err is MissingPeerDependency) {
    // install peer dependencies and retry...
  } else {
    rethrow
  }
}
```

What do you think?

**Comment by Randgalt** [comment]
Live-plugin-manager uses it's own plugin directory and isolate runtimes right? Will the applications installed modules be available?

**Comment by davideicardi** [comment]
> Live-plugin-manager uses it's own plugin directory and isolate runtimes right?
Yes and no. I create a new VM (https://nodejs.org/api/vm.html), but it is not completely isolated from the one of the host. 

> Will the applications installed modules be available?
Yes, by default the packages installed in the "host" are available from the "plugins". You can configure this behavior using `hostRequire` option.

**Comment by Randgalt** [comment]
Well, some handling needs to be done for this. If not this PR, something else.

**Comment by strogonoff** [comment]
Installing `peerDependencies` automatically would be counter-intuitive behavior for people who are used to NPM/Yarn behavior.

From my understanding, it seems like `staticDependencies` could play well with `peerDependencies`.

* package A specifies peer dependency X
* my project requires package A using live-plugin-manager
* live-plugin-manager will not install X
* if my project does **not** pass X via `staticDependencies`, live-plugin-manager will error or warn

(just my 2 cents)

**Comment by davideicardi** [comment]
@strogonoff Yes, I like this. I will create an issue for this and close this PR for now. Thanks!

**Pull request closed without merging**
