### PR TITLE
support repository specified as git://

### PR DESCRIPTION
**Pull request by iurimatias**

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks @iurimatias  for your pull request. May I ask you to implement this feature changing the .ts files?
I have written all the source code using Typescript, .js are just compiled files.

To compile from typescript you just need to run

```
npm install
npm run src-build
```

You can then run `npm test` to check if everything works correctly, eventually by also adding some new unit tests.

thanks!

**Comment by iurimatias** [comment]
@davideicardi sorry my bad, I didn't notice :D

**Comment by davideicardi** [comment]
Thanks!

Your change assume that repository is hosted on github right?

**Comment by iurimatias** [comment]
hi @davideicardi , I somewhat only noticed your comment now... so far as I remember this change was a fix due to live-plugin-manager crashing with git references, I don't recall if it was specific to github or not..

**Comment by davideicardi** [comment]
Closing for inactivity for now. Created an issue to track the request at #26

**Pull request closed without merging**
