### PR TITLE
Fix compatibility issues with JEST and similar frameworks.

### PR DESCRIPTION
**Pull request by fketchakeu**
This PR fixes the following issue:
Since @types\jest adds two additional properties to the NodeRequire function (requireActual, and requireMock),
this causes compatibility issues when using live-plugin-manager in a project that also uses jest.
Since typescript resolves files ending in .ts before files ending in .d.ts, the original src files
are getting compiled each time a consuming project runs tsc. This behavior is undesirable and can
cause compatibility issues since the modified types no longer match.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks @fketchakeu !

Can you just explain me how you solved the problem?
Any reference/documentation/example about these compatibility issues?

I see that you have changed output directory to `dist`, that it is good. But not exactly understant how this will solve your problem.
Using a `dist` directory it is probably good in any case, to have a cleaner solution, but I don't get how this can help ...

**Comment by davideicardi** [comment]
I think also that probably it is better to not put `samples` dir in `dist`. Maybe we can leave it outside, considering it just as a reference/documentation folder...

**Comment by fketchakeu** [comment]
> Thanks @fketchakeu !
> 
> Can you just explain me how you solved the problem?
> Any reference/documentation/example about these compatibility issues?
> 
> I see that you have changed output directory to `dist`, that it is good. But not exactly understant how this will solve your problem.
> Using a `dist` directory it is probably good in any case, to have a cleaner solution, but I don't get how this can help ...

Thanks @davideicardi 
Since the `.ts` files are alongside the `.d.ts` files, the Typescript compiler prioritizes the `.ts` files, and thus will try to recompile the library when the end-user Typescript project being compiled. See https://github.com/microsoft/TypeScript/issues/10704.
When that happens, node type conflicts between the end project and the library will be flagged.

Here is a reproduction that shows the conflict with JEST: https://codesandbox.io/s/node-js-8ggfj (you may have to sign in or to download the project and try to build locally)

I get the following error on build:

```
node_modules/live-plugin-manager/src/PluginVm.ts:189:9 - error TS2739: Type '((requiredName: string) => any) & { resolve: RequireResolve; cache: {}; extensions: RequireExtensions; main: Module; }' is missing the following properties from type 'NodeRequire': requireActual, requireMock

189     const moduleRequire: NodeRequire = Object.assign(
              ~~~~~~~~~~~~~

node_modules/live-plugin-manager/src/PluginVm.ts:205:9 - error TS2741: Property 'path' is missing in type '{ exports: {}; filename: string; id: string; loaded: false; require: NodeRequire; paths: undefined[]; parent: NodeModule; children: undefined[]; }' but required in type 'NodeModule'.

205     const myModule: NodeModule = {
              ~~~~~~~~

  node_modules/@types/node/globals.d.ts:578:9
    578         path: string;
                ~~~~
    'path' is declared here.
```
A solution is to avoid having the `.d.ts` files alongside the `.ts` files in live-plugin-manager.

I hope this helps. Thanks.

**Comment by fketchakeu** [comment]
> I think also that probably it is better to not put `samples` dir in `dist`. Maybe we can leave it outside, considering it just as a reference/documentation folder...

I made the requested change. Don't hesitate to let me know if you have any other question or if another adjustment is needed.
Thanks.

**Comment by davideicardi** [comment]
Thanks for help and explanation!

PR merged and published to npm.

**Pull request merged**
